name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update Submodule
        run: |
          git submodule update --remote --recursive
          git add .
          git commit -m "Update submodule"
          git push
