name: Update Submodule

on:
  push:
    branches:
      - main
    paths:
      - 'zprime_pyrate/**'
      - '.github/workflows/update-submodule.yml'  # Ensure workflow changes also trigger the workflow
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensure submodules are also checked out

      - name: Update Submodule
        run: |
          cd zprime_pyrate  # Navigate to the submodule directory
          git pull origin main --rebase  # Pull the latest changes from the main branch of the submodule
          cd ..  # Navigate back to the main repository directory

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.has_changes == '1'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add zprime_pyrate  # Add the updated submodule to the staging area
          git commit -m "Update submodule zprime_pyrate"
          git push
